name: AWS CloudFormation + Ansible CI/CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    # ------------------------------
    # STEP 1: Checkout Repository
    # ------------------------------
    - name: Checkout Code
      uses: actions/checkout@v3

    # ------------------------------
    # STEP 2: Configure AWS Access
    # ------------------------------
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: us-east-1

    # ------------------------------
    # STEP 3: Deploy Infrastructure
    # ------------------------------
    - name: Deploy CloudFormation Stack
      run: |
        aws cloudformation deploy \
          --template-file cloudformation/ec2.yml \
          --stack-name devops-docker-stack \
          --capabilities CAPABILITY_NAMED_IAM

    # ------------------------------
    # STEP 4: Get EC2 Public IP
    # ------------------------------
    - name: Get Public IP
      id: getip
      run: |
        IP=$(aws cloudformation describe-stacks \
        --stack-name devops-docker-stack \
        --query "Stacks[0].Outputs[0].OutputValue" \
        --output text)
        echo "EC2_IP=$IP" >> $GITHUB_ENV

    # ------------------------------
    # STEP 5: Run Ansible on EC2
    # ------------------------------
    - name: Configure Server & Deploy App
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.EC2_IP }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |

          echo "Connected to EC2"

          # install ansible + git
          sudo apt-get update -y
          sudo apt-get install -y ansible git

          # clone repo fresh
          rm -rf deployrepo
          git clone https://github.com/yuvagiridharan/automated-docker-deployment.git deployrepo

          cd deployrepo

          # run ansible playbook
          ansible-playbook -i ansible/hosts ansible/playbook.yml