- hosts: web
  become: yes
  vars:
    project_dest: "/home/ubuntu/apprepo"
    repo_url: "https://github.com/yuvagiridharan/automated-docker-deployment.git"
    container_name: "myweb"
    image_name: "myweb"

  tasks:
    - name: Update system packages
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install dependencies
      apt:
        name: 
          - docker.io
          - git
        state: present

    - name: Pull latest code from repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ project_dest }}"
        version: main
        force: yes

    - name: Build Docker Image
      command: "docker build -t {{ image_name }} {{ project_dest }}/app"

    - name: Stop and remove old container
      command: "docker rm -f {{ container_name }}"
      ignore_errors: yes

    - name: Run Docker Container
      command: "docker run -d --name {{ container_name }} -p 80:80 --restart always {{ image_name }}"
